name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Compile and package binaries
        run: bash ./build.sh
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: dist/*
